.markdown-doctest-setup.js, README.md, markdown/overview.md, package.json
Fixes several typos/small issues in the documentation as well.
markdown-doctest will now run after mocha as part of npm test. We should also probably get travis set up so that we quickly notice when things break.
=> docs(doctest): Test documentation with markdown-doctest

src/core.ts, tests/stream.ts
As discussed in #11.
Is this what you were thinking @staltz?
=> feat(create): Throw an error if an producer is passed without start and stop

.markdown-doctest-setup.js
Saves anyone having to manually add any in future
=> refactor(doctest): Use markdown-doctest regexRequire to load extras

_includes/footer.html
I'm used to play with the library and prototype at the browser console on it's site (e.g. [Ramda](http://ramdajs.com/docs/), [Moment](http://momentjs.com/), [Immutable](https://facebook.github.io/immutable-js/)). So the workflow is simple: check docs, open browser console, try it.
[xstream docs](http://staltz.com/xstream/) currently lacks this feature
This PR exposes `xstream` and `xs` to the global window object. It also adds nice console banner (shamefully based on the immutable one)
=> Add browser console playground

src/extra/fromEvent.ts, tests/extra/fromEvent.ts
Add support for stream generation from EventEmitters. 
`fromEvent` will accept as a first argument either a DOMElement or an EventEmitter. When providing `fromEvent` with an EventEmitter, the third argument (useCapture) is always ignored.
There are two potentially outstanding concerns.
**First**: This is my first contribution to xtream and I'm not familiar with how the documentation is built. I've updated JSDOC comments with new examples, but it's possible that my comments don't work with the documentation generator.
**Second**: Parity with RxJS and Most.js should probably involve a change to the third parameter here. I believe they support an object with configuration options, rather than a boolean. I'm not certain if that work would be a requirement to merge, but a brief discussion …
=> Support NodeJS Event Emitters in fromEvent extra

src/core.ts, tests/factory/merge.ts
This is intended to fix #74 
The problem it that case is that `MergeProducer#_stop` method never gets called because of cancelled async stoppage. So when original stream gets executed second time and then completed, the `ac` counter goes to -1 and that doesn't lead to merged stream completion.
The idea of PR is that we can be sure about (virtual) count of active listeners right before we iterate through `insArr` and call `_add`s, because each of the incoming streams either runs already or gets started by `_add`.
There's still a potential problem in case if some incoming stream gets restarted by another listener. To fix that, `merge` should be rewritten in the manner of `combine` to track which of the streams actually completes.
=> fix xs.merge completion

src/core.ts, tests/factory/merge.ts
Support type declarations when calling `xs.merge()`. This change allows consumers to leverage TypeScript to verify type safety when merging streams. It also brings `merge` in line with other static methods which already support this feature.
Modify static `merge` method to implement a new interface: MergeSignature. This interface is constructed similarly to the CombineSignature interface. Export the new interface.
There are two areas I think merit discussion.
**First**: I'm not exactly sure what the intended behavior of this method is when called without arguments. The interface says a stream is returned that emits items of any type. And I suppose that's true. However, when I call this without any arguments, I get a stream that doesn't emit anything ever (or complete). Obviously my fault …
=> Introduce xs.merge type declaration

src/extra/fromEvent.ts, tests/extra/fromEvent.ts
If provided with an EventEmitter, `fromEvent` streams will emit an array of values when the EventEmitter provides listeners with multiple arguments.
The previous implementation naively provided only the first argument, which made `fromEvent` incompatible with event interfaces that rely on providing multiple arguments to their listeners, such as Node's `http.Server`.
An alternative solution involved providing selector support. This wasn't implemented for several reasons.
1. Modifying the function signature for the extra would be a breaking change.
2. An expanded function signature would become 'crowded', and one of the architectural goals of xstream is to keep interfaces as small as they need to be to achieve their goals.
3. Aggregating emitted events into an array is consistent with the …
=> feat(fromEvent): Aggregate multiple arguments

src/extra/dropRepeats.ts, tests/extra/dropRepeats.ts
Ran into a tricky behavior tonight when feeding @cycle/history into itself: if we have a circular dependency, and the event emitted by `dropRepeats` triggers another input event in the same stream, we can get into an infinite loop. The `dropRepeats` operator will recurse because it emits before it updates its sentinel value until it overflows the stack.
This test seems to model the case I hit accurately, but the way it checks for completion feels a bit inelegant -- any suggestions? I tried using `endWith(input.last())` but that appeared to cause `stream` to complete without emitting any events.
=> fix(dropRepeats): handle circular dependencies

src/core.ts, tests/factory/merge.ts, tests/memoryStream.ts, tests/operator/flatten.ts, tests/stream.ts
To fix bugs such as #91 and others where adding .debug() would magically solve the bug, we need to change the semantics around producer stop and stream completion/error. Previously, a stream would complete first, and stop the producer after. Now, the stream stops its producer just before completing. This was important to make the test 'Stream.prototype.flatten with map should not run multiple executions of the inner' pass.
BREAKING CHANGE: in this version, when a stream completes or errors, its producer has already been stopped. In previous versions, the stream first completes, propagates the complete to other
listeners and operators, and then its producer is stopped. You may barely notice this breaking change when updating your code. Most existing code will still work like before.
- - - …
=> fix(core): teardown and stop producer before complete/error

src/core.ts
If a type-guard is passed to filter, you know that the returned stream contains
only elements of the type that is checked by the type-guard.
=> support type-guards in Stream's filter method

package.json, src/core.ts, src/index.ts, tests/factory/from.ts, tests/factory/fromObservable.ts, tests/stream.ts
Implements basic interop that is compatible with most.js and RxJS 5. 
Add `xs.fromObservable(observable)` method that will take an Observable and return an xstream `Stream`.
Add `xs.from(input)` for Observable interop, which will convert Arrays, Observable, and Promises using their respective fromX method.
Add `subscribe` method to Stream that return a Subscription with `unsubscribe`
Add `Symbol.observable` ponyfill `symbol-observable` as a dependency to use the same as most.js and RxJS 5.
Add tests for all of the above.
=> feat(Observable): Adds Basic Observable interop

markdown/footer.md, src/core.ts, src/extra/sampleCombine.ts, tests/extra/sampleCombine.ts, tsconfig.json
Add an extra named `sampleCombine`. This extra is designed to provide parity with the [`withLatestFrom`](http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#instance-method-withLatestFrom) operator, and similar operators, in other stream libraries.
SampleCombine combines a source stream with multiple other streams. The result stream will emit the latest events from all input streams, but only when the source stream emits.
If the source, or any input stream, throws an error, the result stream will propagate the error. If any input streams end, their final emitted value will remain in the array of any subsequent events from the result stream (this behavior is consistent with the implementation in Rx). The result stream will only complete upon completion of the source stream. …
=> Implement `sampleCombine` extra

src/extra/delay.ts, src/extra/dropRepeats.ts, src/extra/dropUntil.ts, src/extra/split.ts, tests/extra/dropUntil.ts, tests/operator/endWhen.ts, tests/operator/imitate.ts
A little bit breaking because `delay` doesn't not allow to specify type, so one will have to fix it in the codebase.
=> improve TypeScript typings for delay, dropRepeats, dropUnti, split

src/extra/throttle.ts, tests/extra/throttle.ts
Adds throttle extra operator
```js
/**
* Emits event and drops subsequent events until a certain amount of silence has passed.
*
* Marble diagram:
*
* ```text
* --1-2-----3--4----5|
*     throttle(60)
* --1-------3-------5-|
*/
```
=> feat(throttle): add throttle extra operator

src/core.ts, tests/operator/imitate.ts
This prevents `Stream` from swallowing errors if no `Listener` is attached.
=> Throw error if no listener is attached #121

src/index.ts, tests/operator/take.ts
This fixes #158 but IMO `imitate` still not a good interface, though.  
It is very special operator distinct with other operators.
=> bug: unterminated take operator

src/index.ts
This corresponds to  
https://github.com/ReactiveX/rxjs/pull/2505  
Promise definition is not compatible with Promise implementations out there.  
I think the type should be relaxed.  
I can add more test like what I did in rxjs but I think the type itself should suffice.  
Poke me if you think the test is necessary.
=> Relax promise typing

src/index.ts
=> Fix typo in debug description

src/extra/dropRepeats.ts
Little optimization to extra/dropRepeats to set equality function only inside constructor, not
checking it on every call to isEq, plus some bytes saved in code and deleting an unused public
variable (this.fn) from class.
=> perf(extra/dropRepeats): Optimize set equality check function only inside constructor

README.md, src/index.ts, tests/factory/combine.ts
Updated combine docs removing Note and related Comments inside code, becouse according to release 10.3.0 ([e8b2eef](https://github.com/staltz/xstream/commit/e8b2eef)) now it will emit a new Array instance, so the .map trick is no more needed. Added even a test to prove it.
=> docs(combine): Update combine docs removing Note about array instance

package.json
Next version up is 1.1.0 which causes tsc to fail compilation with
error TS2451: Cannot redeclare block-scoped variable 'Symbol'.
Appears to be related to benlesh/symbol-observable#34
=> Lock symbol-observable to 1.0.4.

package.json, yarn.lock
just updating to the latest symbol-observable now that https://github.com/benlesh/symbol-observable/issues/34 is resolved.
=> chore(symbol-observable): update to 1.2.0

src/index.ts
In fromObservable, use Symbol.observable if present to get observable. If not present,treat received
object as a subscribable (current behaviour).
Some observables passed to `xs.fromObservable` might not have a `subscribe` method. It is also an issue for packages like `redux` or `router5` which have / might have a `subscribe` method with a different interface than observables (accepting listener functions rather than objects).
Note that `xs.fromObservable` accepts subscribables, but `xs.from` doesn't.
=> use Symbol.observable to get observable

src/index.ts
=> Use export default xs to enable autoimport in VSCode

_includes/footer.html
GitHub doesn't serve the xstream file with a correct mimetype, so it wouldn't load.
Loading from unpkg.com solves that, and it loads the files from the npm package so it will be kept up-to-date.
=> Use xstream from npm in website

_config.yml
Chrome won't load the stylesheet because it refers to an non-secure resource
=> Use https in the website resources

src/index.ts
using arrow syntax for those methods which will
be overridden by interface extention sometimes
cause compile error. Fix by stop using arrow syntax
When I tried to use xstream in my library, it caused error like this
```
../../node_modules/xstream/index.d.ts:15:18 - error TS2430: Interface 'Operator<T, R>' incorrectly extends interface 'InternalProducer<R>'.
Types of property '_start' are incompatible.
Type '(out: Stream<R>) => void' is not assignable to type '(listener: InternalListener<R>) => void'.
Types of parameters 'out' and 'listener' are incompatible.
Type 'InternalListener<R>' is not assignable to type 'Stream<R>'.
Property '_prod' is missing in type 'InternalListener<R>'.
15 export interface Operator<T, R> extends InternalProducer<R>, InternalListener<T>, OutSender<R> {
~~~~~~~~ …
```
=> fix(types): do not use arrow syntax for _start

src/extra/dropUntil.ts, tests/extra/dropUntil.ts
Refactor `dropUntil` to leave its output stream unchanged when its 'other' stream completes. Make output stream empty if 'other' stream is empty.
This change aligns `dropUntil` more closely with the [`skipUntil` operator from rxjs.](https://github.com/ReactiveX/rxjs/blob/37d9ea9a8665d0c4b6593da4c237e037e98f66b5/spec/operators/skipUntil-spec.ts)
The other internal listener in `dropUntil` now treats completion as a `noop`. Additionally, when source completes, we no longer call `up()`, which seems like a pretty major bug to begin with.
Instead, completion of the source now calls `_stop()`, which removes the internal listener to source and detaches the output stream from the operator. **This is definitely a situation where we need ComVer, since consumers may have unknowingly relied on this …
=> fix(dropUntil): align with rxjs skipUntil

src/extra/debounce.ts, tests/extra/debounce.ts
Emit any pending value, then complete, if a source stream completes before a debounce interval closes.
In order to be able to emit the latest value upon completion, the operator needs access to the most recent value. In the previous implementation, the emission took place in a closure created by `setTimeout`, so now the operator has a new property `t` which keeps track of this emission.
This value is cleared when the debounce interval closes and upon completion.
Resolve #257.
Probably should close #127.
=> feat(debounce): emit pending value on completion

_config.yml, _includes/footer.html
Currently the stylesheet is not loading when you visit the website with https as it's trying to load the stylesheet from http. Also, GitHub does not allow do use raw files directly. AFAIK this should fix both.
=> Fix styling of website

src/extra/flattenConcurrentlyAtMost.ts, tests/extra/flattenConcurrentlyAtMost.ts
Add flattenSequentiallyAtMost(n) extra.
Add new extra operator file and unit tests. The operator extra started as a copy of `flattenConcurrently` wrapped in a factory function. From there, a few renames and some combined functionality from `flattenSequentially` to implement the inner buffer/queue named `_seq`.
There are some distinctions between both, obviously. The completion method (`_c`) needs to be able to determine if there are any currently connected streams, or any streams in the buffer. If the answer to both questions is no, then we send a completion event downstream.
Additionally, there may be a case when the last inner stream completes, there's no items left in the queue, and the meta stream has completed. This also means we should send a completion event downstream.
To track …
=> feat(flattenConcurrentlyAtMost): add new extra

src/index.ts
Add `combine` method typed signature. Allows getting a typed result when combining a list of homogeneous streams.
```
const item$s = items.map(item => xs.of(item))
const items$ = xs.combine(...items) // <= Stream<Items[]>
```
=> Add combine typed signature

src/extra/flattenConcurrently.ts, src/extra/flattenConcurrentlyAtMost.ts, src/extra/flattenSequentially.ts, src/index.ts
const mm$ = xs.createWithMemory<MemoryStream<number>>()
const sm$ = xs.create<MemoryStream<number>>()
const ms$ = xs.createWithMemory<Stream<number>>()
const ss$ = xs.create<Stream<number>>()
const fmm$ = mm$.flatten() // without fix this is typed to Stream<{}> not Stream<number>
const fsm$ = sm$.flatten()
const fms$ = ms$.flatten()
const fss$ = ss$.flatten()
=> fix typings for later TS versions (3.4)

_includes/head.html
Fixes #279 
I haven't really tested it by building the site because I don't know how to do that but replacing `/css/main.css` to `css/main.css` using dev-tools worked.
Maybe this bookmarklet would help to test: `javascript:document.querySelector('link[href="/css/main.css"]').setAttribute("href", "css/main.css")`
=> Fixes issue #279

yarn.lock
While working on #287, I've noticed that [visionmedia/dox](https://github.com/visionmedia/dox) is now [tj/dox](https://github.com/tj/dox) (maybe transferred?), causing integration check failures on `yarn install`.
I've updated URL for the tarball specified in `yarn.lock`.
=> Update URL for dox

src/extra/debounce.ts
There is a possible bug when timer is set (not yet executed) and stream stopped. If timer interval is not cleared it results in infinite emitting (not sure why emitting is looped).
I don't have a clean simple repro example, but it happened in my app, had to debug it. 
Anyway it seems logical to clear not executed emit interval on `stop`, and not to clear it is a potential problem.
=> debounce: clear emit timer interval on stop

src/index.ts
This would allow such things without typing issues:
```ts
declare const $some: Stream<number> | undefined
($some || xs.empty<number>()).map(x => -x)
```
=> feat: add never and empty <T = any> param

package.json, src/index.ts, yarn.lock
This upgrade brings xstream into the set of npm packages that can be safely run without any mutation of primordial prototypes. Such packages can be used in applications that freeze the prototypes to mitigate prototype pollution supply chain attacks.  For example, `xstream` is in the supply chain for the CosmJS financial instruments project and would benefit from such safety measures.
This is considered a breaking change on account of the unlikely possibility that a platform exists that does not support both Symbol and Symbol.for. This hypothetical platform would no longer be supported.
Closes #312
=> chore(deps): Upgrade symbol-observable to version 2
